#!/bin/bash
#
# Run a command over and over until it exits 0. If DELAY is set, wait $DELAY
# seconds between attempts. If MAXRETRIES is set, fail after that many attempts

# Default to 5 tries with 5 seconds between attempts

if [ -z $DELAY ]; then
  DELAY=5
fi

if [ -z $MAXRETRIES ]; then
  MAXRETRIES=5
fi

if [ "$1" == "--help" ] ; then
  echo "$0 command"
  echo "or"
  echo "DELAY=30 MAXRETRIES=10 $0 command"
  echo
  echo "Keep trying command until it succeeds. Wait DELAY seconds between attempts"
  echo "and make up to MAXRETRIES attempts"
  echo
  echo "DELAY defaults to 5 seconds, and MAXRETRIES defaults to 5 attempts."
  echo
  exit 0
fi

attempts=0
while true
do
  (( attempts = $attempts +1 ))
  $*
  exitcode=$?
  if [[ $exitcode == 0 ]]; then
    exit 0
  else
    echo "'$*' attempt $attempts failed; waiting to retry..."
    if [ ! -z $MAXRETRIES ]; then
      if (( $attempts >= $MAXRETRIES )); then
        echo "max retries was $MAXRETRIES, $attempts failed attempts, exiting..."
        exit $exitcode
      fi
    fi
    echo
    sleep ${DELAY}
  fi
done
