"""init

Revision ID: 37b2905be989
Revises: None
Create Date: 2014-10-21 19:04:33.924914

"""

# revision identifiers, used by Alembic.
revision = '37b2905be989'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_stats',
    sa.Column('metric', sa.VARCHAR(length=190), nullable=False),
    sa.Column('agg_ts', sa.DATETIME(), nullable=False),
    sa.Column('scale', mysql.DOUBLE(), nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first', sa.DATETIME(), nullable=True),
    sa.Column('last', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('metric', 'agg_ts')
    )
    op.create_table('wordpress',
    sa.Column('uid', sa.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=40), nullable=False),
    sa.Column('title', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('text', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('msg', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('tumblr',
    sa.Column('uid', sa.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=40), nullable=False),
    sa.Column('text', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('msg', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('twitter',
    sa.Column('uid', sa.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('retweet', sa.BOOLEAN(), nullable=False),
    sa.Column('text', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('msg', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('ref_uid', sa.VARCHAR(length=40), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('wordpress_samples',
    sa.Column('metric', sa.VARCHAR(length=190), nullable=False),
    sa.Column('msg_uid', sa.VARCHAR(length=40), server_default='', nullable=False),
    sa.Column('agg_ts', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['msg_uid'], [u'wordpress.uid'], name='wordpress_samples_to_wordpress_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric', 'msg_uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('tumblr_samples',
    sa.Column('metric', sa.VARCHAR(length=190), nullable=False),
    sa.Column('msg_uid', sa.VARCHAR(length=40), server_default='', nullable=False),
    sa.Column('agg_ts', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['msg_uid'], [u'tumblr.uid'], name='tumblr_samples_to_tumblr_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric', 'msg_uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('twitter_samples',
    sa.Column('metric', sa.VARCHAR(length=190), nullable=False),
    sa.Column('msg_uid', sa.VARCHAR(length=40), server_default='', nullable=False),
    sa.Column('agg_ts', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['msg_uid'], [u'twitter.uid'], name='twitter_samples_to_twitter_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric', 'msg_uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_samples')
    op.drop_table('tumblr_samples')
    op.drop_table('wordpress_samples')
    op.drop_table('twitter')
    op.drop_table('tumblr')
    op.drop_table('wordpress')
    op.drop_table('agg_stats')
    ### end Alembic commands ###
