"""twitter datasource

Revision ID: 587c485d8be
Revises: 37b2905be989
Create Date: 2014-11-10 15:16:27.390340

"""

# revision identifiers, used by Alembic.
revision = '587c485d8be'
down_revision = '37b2905be989'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_tweets',
    sa.Column('uid', sa.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('retweet', sa.BOOLEAN(), nullable=False),
    sa.Column('lang', sa.VARCHAR(length=10), nullable=False),
    sa.Column('text', mysql.MEDIUMTEXT(convert_unicode=True), nullable=True),
    sa.Column('ref_uid', sa.VARCHAR(length=40), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    op.create_table('twitter_tweet_samples',
    sa.Column('metric', sa.VARCHAR(length=190), nullable=False),
    sa.Column('msg_uid', sa.VARCHAR(length=40), server_default='', nullable=False),
    sa.Column('agg_ts', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['msg_uid'], [u'twitter_tweets.uid'], name='twitter_tweet_samples_to_twitter_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric', 'msg_uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_tweet_samples')
    op.drop_table('twitter_tweets')
    ### end Alembic commands ###
