"""rename datasift tables

Revision ID: 235df5f94f20
Revises: 587c485d8be
Create Date: 2014-11-10 15:30:41.005652

"""

# revision identifiers, used by Alembic.
revision = '235df5f94f20'
down_revision = '587c485d8be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('twitter', 'datasift_tweets')
    op.rename_table('twitter_samples', 'datasift_tweet_samples')
    op.rename_table('wordpress', 'datasift_wordpress_msgs')
    op.rename_table('wordpress_samples', 'datasift_wordpress_samples')
    op.rename_table('tumblr', 'datasift_tumblr_msgs')
    op.rename_table('tumblr_samples', 'datasift_tumblr_samples')
    op.rename_table('agg_stats', 'datasift_agg_stats')
    ### end Alembic commands ###


def downgrade():
    op.rename_table('datasift_tweets', 'twitter')
    op.rename_table('datasift_tweet_samples', 'twitter_samples')
    op.rename_table('datasift_wordpress_msgs', 'wordpress')
    op.rename_table('datasift_wordpress_samples', 'wordpress_samples')
    op.rename_table('datasift_tumblr_msgs', 'tumblr')
    op.rename_table('datasift_tumblr_samples', 'tumblr_samples')
    op.rename_table('datasift_agg_stats', 'agg_stats')
    ### end Alembic commands ###
