"""add twitter deletion table

Revision ID: 77c96aa1615
Revises: 5809f092058
Create Date: 2015-01-08 20:17:36.849509

"""

# revision identifiers, used by Alembic.
revision = '77c96aa1615'
down_revision = '5809f092058'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_deletion',
    sa.Column('tweet_uid', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('userid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=False),
    sa.PrimaryKeyConstraint('tweet_uid'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    ### end Alembic commands ###


def downgrade():
  raise NotImplementedError("Rollback is not supported.")
