"""add emitted sample table

Revision ID: 4bd7cf179841
Revises: 77c96aa1615
Create Date: 2015-01-27 07:18:02.380216

"""

# revision identifiers, used by Alembic.
revision = '4bd7cf179841'
down_revision = '77c96aa1615'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emitted_sample_tracker',
    sa.Column('key', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50), nullable=False),
    sa.Column('sample_ts', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emitted_sample')
    ### end Alembic commands ###
