"""generate new schema for twitter handle failures

Revision ID: b1195080a26
Revises: 2b44dfda0019
Create Date: 2015-02-03 10:18:25.286571

"""

# revision identifiers, used by Alembic.
revision = 'b1195080a26'
down_revision = '2b44dfda0019'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_handle_failures',
    sa.Column('handle', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('handle'),
    mysql_CHARSET='utf8',
    mysql_COLLATE='utf8_unicode_ci'
    )
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Rollback is not supported.")
