"""security news details

Revision ID: 52e7bfdf50f7
Revises: b1195080a26
Create Date: 2015-02-09 22:45:34.254006

"""

# revision identifiers, used by Alembic.
revision = '52e7bfdf50f7'
down_revision = 'b1195080a26'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # *********************************
    # xignite_security_headline schema
    # *********************************
    op.add_column('xignite_security_headline', sa.Column('summary', mysql.TEXT(convert_unicode=True), nullable=True))
    op.add_column('xignite_security_headline', sa.Column('orig_pub_time', sa.DATETIME(), nullable=True))
    op.add_column('xignite_security_headline', sa.Column('orig_source', mysql.TEXT(convert_unicode=True), nullable=True))
    op.add_column('xignite_security_headline', sa.Column('details_proc_dur', sa.FLOAT(), nullable=True))

    #
    # Add source column to primary key
    #

    # Create temporary index on foreign key symbol before dropping primary key
    # to work around bug in mysql; see http://bugs.mysql.com/bug.php?id=20525
    op.create_index('symbol_temp_idx', 'xignite_security_headline', ['symbol'], unique=False)
    # Add source column to primary key
    op.drop_constraint('primary', 'xignite_security_headline', type_='primary')
    # `source` column was too big for primary key at 500 utf8 chars
    op.alter_column('xignite_security_headline', 'source',
                    type_=mysql.VARCHAR(length=190),
                    existing_nullable=False)
    op.create_primary_key(
        'xignite_security_headline_pk', 'xignite_security_headline',
        ['symbol', 'local_pub_date', 'url', 'source'])
    op.drop_index('symbol_temp_idx', 'xignite_security_headline')

    #
    # Add index on discovered_at column
    #
    op.create_index('discovered_at_idx', 'xignite_security_headline', ['discovered_at'], unique=False)


    # *********************************
    # xignite_security_release schema
    # *********************************
    op.add_column('xignite_security_release', sa.Column('summary', mysql.TEXT(convert_unicode=True), nullable=True))
    op.add_column('xignite_security_release', sa.Column('orig_pub_time', sa.DATETIME(), nullable=True))
    op.add_column('xignite_security_release', sa.Column('orig_source', mysql.TEXT(convert_unicode=True), nullable=True))
    op.add_column('xignite_security_release', sa.Column('details_proc_dur', sa.FLOAT(), nullable=True))

    #
    # Add source column to primary key
    #

    # Create temporary index on foreign key symbol before dropping primary key
    # to work around bug in mysql; see http://bugs.mysql.com/bug.php?id=20525
    op.create_index('symbol_temp_idx', 'xignite_security_release', ['symbol'], unique=False)
    op.drop_constraint('primary', 'xignite_security_release', type_='primary')
    # `source` column was too big for primary key at 500 utf8 chars
    op.alter_column('xignite_security_release', 'source',
                    type_=mysql.VARCHAR(length=190),
                    existing_nullable=False)
    op.create_primary_key(
        'xignite_security_release_pk', 'xignite_security_release',
        ['symbol', 'local_pub_date', 'url', 'source'])
    op.drop_index('symbol_temp_idx', 'xignite_security_release')

    #
    # Add index on discovered_at column
    #
    op.create_index('discovered_at_idx', 'xignite_security_release', ['discovered_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Rollback is not supported.")
