"""add company_symbol_failures

Revision ID: 52c6989ed12e
Revises: 52e7bfdf50f7
Create Date: 2015-02-13 14:42:17.130227

"""

# revision identifiers, used by Alembic.
revision = '52c6989ed12e'
down_revision = '52e7bfdf50f7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_symbol_failures',
    sa.Column('symbol', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )



def downgrade():
    raise NotImplementedError("Rollback is not supported.")
