"""track emitted non-metrics

Revision ID: 3014f946c794
Revises: 161a3074ac8f
Create Date: 2015-02-17 16:26:04.183124

"""

# revision identifiers, used by Alembic.
revision = '3014f946c794'
down_revision = '161a3074ac8f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emitted_non_metric_tracker',
    sa.Column('key', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50), nullable=False),
    sa.Column('last_seq', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key')
    )

    # Add auto-incrementing sequence column in twitter_tweet_samples. Since
    # AUTO_INCREMENT column must be primary key in mysql, drop the current
    # primary key and repalce it with a unuque index.
    #
    # NOTE: Since alembic presently doesn't support multiple
    # alter_specifications per ALTER TABLE statement, it would take too many
    # hours to execute the following logic in individual ALTER TABLE statements
    # on the 12+ million row table. So, we construct SQL by hand to work around
    # this.
    op.execute(
        "ALTER TABLE `twitter_tweet_samples` "
        "DROP PRIMARY KEY, "
        "ADD COLUMN `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, "
        "ADD PRIMARY KEY(`seq`), "
        "ADD UNIQUE INDEX `metric_and_msg_uid_idx` (`metric`, `msg_uid`)"
    )
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Rollback is not supported.")
