"""xignite stock data

Revision ID: 442de3177362
Revises: 3014f946c794
Create Date: 2015-02-25 15:43:52.008400

"""

# revision identifiers, used by Alembic.
revision = '442de3177362'
down_revision = '3014f946c794'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xignite_security_bars',
    sa.Column('symbol', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=20), nullable=False),
    sa.Column('StartDate', sa.DATE(), nullable=False),
    sa.Column('StartTime', sa.TIME(), nullable=False),
    sa.Column('EndDate', sa.DATE(), nullable=False),
    sa.Column('EndTime', sa.TIME(), nullable=False),
    sa.Column('UTCOffset', sa.FLOAT(), nullable=False),
    sa.Column('Open', sa.FLOAT(), nullable=False),
    sa.Column('High', sa.FLOAT(), nullable=False),
    sa.Column('Low', sa.FLOAT(), nullable=False),
    sa.Column('Close', sa.FLOAT(), nullable=False),
    sa.Column('Volume', sa.INTEGER(), nullable=False),
    sa.Column('Trades', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], [u'xignite_securty.symbol'], name='xignite_security_bars_to_security_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'StartDate', 'StartTime', 'EndDate', 'EndTime', 'UTCOffset')
    )
    op.create_table('emitted_stock_volume',
    sa.Column('symbol', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=20), nullable=False),
    sa.Column('StartDate', sa.DATE(), nullable=False),
    sa.Column('StartTime', sa.TIME(), nullable=False),
    sa.Column('EndDate', sa.DATE(), nullable=False),
    sa.Column('EndTime', sa.TIME(), nullable=False),
    sa.Column('UTCOffset', sa.FLOAT(), nullable=False),
    sa.Column('sent', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['symbol', 'StartDate', 'StartTime', 'EndDate', 'EndTime', 'UTCOffset'], ['xignite_security_bars.symbol', 'xignite_security_bars.StartDate', 'xignite_security_bars.StartTime', 'xignite_security_bars.EndDate', 'xignite_security_bars.EndTime', 'xignite_security_bars.UTCOffset'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'StartDate', 'StartTime', 'EndDate', 'EndTime', 'UTCOffset')
    )
    op.create_index('xignite_stock_volume_sent_idx', 'emitted_stock_volume', ['sent'], unique=False)
    op.create_table('emitted_stock_price',
    sa.Column('symbol', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=20), nullable=False),
    sa.Column('StartDate', sa.DATE(), nullable=False),
    sa.Column('StartTime', sa.TIME(), nullable=False),
    sa.Column('EndDate', sa.DATE(), nullable=False),
    sa.Column('EndTime', sa.TIME(), nullable=False),
    sa.Column('UTCOffset', sa.FLOAT(), nullable=False),
    sa.Column('sent', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['symbol', 'StartDate', 'StartTime', 'EndDate', 'EndTime', 'UTCOffset'], ['xignite_security_bars.symbol', 'xignite_security_bars.StartDate', 'xignite_security_bars.StartTime', 'xignite_security_bars.EndDate', 'xignite_security_bars.EndTime', 'xignite_security_bars.UTCOffset'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'StartDate', 'StartTime', 'EndDate', 'EndTime', 'UTCOffset')
    )
    op.create_index('xignite_stock_price_sent_idx', 'emitted_stock_price', ['sent'], unique=False)
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Rollback is not supported.")
