#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

NUMENTA=/opt/numenta
AMI_TEST_D="${NUMENTA}/YOMP/tests/py/ami"
TEST_DRIVER="${NUMENTA}/YOMP/run_tests.sh"

if [ ! -d "${AMI_TEST_D}" ]; then
  echo "${AMI_TEST_D} not found."
  exit 1
fi

cd "${NUMENTA}/YOMP"

# Setup environment to match ec2-user's
source ~ec2-user/.bashrc
source ~ec2-user/.bash_profile
export PYTHONPATH="$PYTHONPATH:/opt/numenta/anaconda/lib/python2.7/site-packages"

exec "${TEST_DRIVER}" --language py --results xunit jenkins --ami --verbose
