#!/bin/sh
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
#
# Tickle YOMP, but only if we've already set up YOMP. Makes supervisord run
# 'start all' so any processes have died are restarted.

NUMENTA=/opt/numenta
YOMP_APP_CONF="${NUMENTA}/YOMP/conf/YOMP-api.conf"

if [ "$(/usr/bin/id -u)" -ne 0 ]; then
  echo "You are not root"
  exit 1
fi

if [ ! -f "${YOMP_APP_CONF}" ]; then
  echo "YOMP has not been configured yet"
  exit 0
fi

service YOMPservices tickle
