#!/bin/sh
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Run our AMI tests with nose. Exec so our callers get the nose exit code.
if [ "$(/usr/bin/id -u)" -ne 0 ]; then
  echo "You must be root or use sudo to run run-ami-tests."
  exit 1
fi

echo "Some of the shellshock tests print error messages - they're supposed"
echo "to, that means that the tests failed when they tried to exploit the"
echo "shellshock bugs."
echo
echo "As long as nose prints OK at the end and returns 0, things are good."
echo
echo

exec /opt/numenta/anaconda/bin/nosetests -w /etc/numenta/tests --exe --verbose
