#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Webserver specific cleanups.

echo
echo "********************************"
echo "Cleaning webserver AMI candidate"
echo "********************************"

echo
echo "********************************"
echo "Zapping webroots"
rm -frv /opt/numenta/YOMP/live /opt/numenta/YOMP/staging

echo
echo "********************************"
echo "Zapping logfiles..."
logger -t image-cleanup "Zapping logfiles..."
for logf in /var/log/nginx/*
do
  echo "Resetting ${logf}"
  cat /dev/null > "${logf}"
done
