#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
#
# This should only contain settings specific to webserver AMIs.

echo "Marking instance as being an AMI build..."
AMIBUILD_LOCK=/tmp/baking-ami
touch "${AMIBUILD_LOCK}"

echo "Configuring Salt minion_id"
echo
echo "Setting Salt minion_id to webserver-amibake"
echo webserver-amibake > /etc/salt/minion_id

echo "Installing secretsauce repo..."
mv /tmp/secretsauce.repo /etc/yum.repos.d

yum install -y webserver-saltcellar

echo "Running Salt..."
salt-call --local state.highstate -l debug
saltcode=$?
echo
echo "Salt run return code: ${saltcode}"
exit "${saltcode}"
