#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
#
# This should only contain settings specific to YOMP Plumbing AMIs

echo "Marking instance as being an AMI build..."
AMIBUILD_LOCK=/tmp/baking-ami
touch "${AMIBUILD_LOCK}"

install-prerequisites-and-update-repos() {
  echo "Purging old YOMP repo file..."
  rm -f /etc/yum.repos.d/YOMP.repo

  echo "Installing S3 support for yum..."
  yum install -y /tmp/yum-s3-0.2.4-1.noarch.rpm

  echo "Cleaning up stale yum data..."
  yum clean all

  # If you install these before installing yum-s3, yum will crash on start.
  for repo in YOMP-development.repo \
              YOMP-release-candidates.repo \
              YOMP-releases.repo \
              nta-carbonite.repo \
              nta-thirdparty.repo
  do
    echo "Installing ${repo}..."
    mv "/tmp/${repo}" /etc/yum.repos.d
  done
}

run-salt() {
  echo "Configuring Salt minion_id"
  echo
  echo "Setting Salt minion_id to YOMP-plumbing"
  echo YOMP-plumbing > /etc/salt/minion_id

  yum install -y YOMP-saltcellar

  echo "Running Salt..."
  salt-call --local state.highstate -l debug
  saltcode=$?
  echo
  echo "Salt run return code: ${saltcode}"
  exit "${saltcode}"
}

install-prerequisites-and-update-repos
run-salt
