#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
# Install devtools

echo "Installing developer tools..."
echo "Installing devtools-2.repo..."
cp -v /tmp/devtools-2.repo /etc/yum.repos.d
cp -v /tmp/devtools-pathaddition.sh /etc/profile.d

yum makecache

yum install -y cmake \
  devtoolset-2-binutils \
  devtoolset-2-gcc \
  devtoolset-2-gcc-c++ \
  libjpeg-turbo-devel \
  libX11-devel \
  libXt-devel \
  openssl-devel \
  rpm-build
