#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Mixed mode shows only one line of output for state changes that succeeded,
# then does verbose output on ones that don't. Otherwise we get verbose output
# for everything, which makes it harder to find the bad states.

current_state_output=$(grep 'state_output: mixed' /etc/salt/minion)
if [ -z "${current_state_output}" ]; then
  echo "Setting salt output state to mixed"
  echo "state_output: mixed" >> /etc/salt/minion
fi
