"""init

Revision ID: 556b9074c064
Revises: None
Create Date: 2015-03-31 17:18:51.002030

"""

# revision identifiers, used by Alembic.
revision = "556b9074c064"
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql



def upgrade():
  # commands auto generated by Alembic - please adjust!
  op.create_table("monitor_error_flags",
                  sa.Column("uid", mysql.VARCHAR(length=40), nullable=False),
                  sa.Column("name", mysql.VARCHAR(length=40), nullable=False),
                  sa.Column("should_report", sa.BOOLEAN(), nullable=False),
                  sa.Column("last_occurrence", sa.DATETIME(),
                            server_default=sa.text(u"CURRENT_TIMESTAMP"),
                            nullable=False),
                  sa.Column("occurrence_count", sa.INTEGER(), nullable=True),
                  sa.PrimaryKeyConstraint("uid",
                                          name="monitor_error_flags_pk"),
                  mysql_CHARSET="utf8",
                  mysql_COLLATE="utf8_unicode_ci")
  # end Alembic commands



def downgrade():
  raise NotImplementedError("Rollback is not supported.")
