"""adding extension allowing an error flag table for each monitor

Revision ID: b6bac808f77
Revises: 556b9074c064
Create Date: 2015-05-26 11:48:26.088077

"""

# revision identifiers, used by Alembic.
revision = "b6bac808f77"
down_revision = "556b9074c064"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table("metric_order_monitor_error_flags",
    sa.Column("uid", mysql.VARCHAR(length=40), nullable=False),
    sa.Column("name", mysql.VARCHAR(length=40), nullable=False),
    sa.Column("should_report", sa.BOOLEAN(), nullable=False),
    sa.Column("last_occurrence", sa.DATETIME(),
              server_default=sa.text(u"CURRENT_TIMESTAMP"), nullable=False),
    sa.Column("occurrence_count", sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint("uid", name="metric_order_monitor_error_flags_pk"),
    mysql_CHARSET="utf8",
    mysql_COLLATE="utf8_unicode_ci"
    )
    op.create_table("models_monitor_error_flags",
    sa.Column("uid", mysql.VARCHAR(length=40), nullable=False),
    sa.Column("name", mysql.VARCHAR(length=40), nullable=False),
    sa.Column("should_report", sa.BOOLEAN(), nullable=False),
    sa.Column("last_occurrence", sa.DATETIME(),
              server_default=sa.text(u"CURRENT_TIMESTAMP"), nullable=False),
    sa.Column("occurrence_count", sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint("uid", name="models_monitor_error_flags_pk"),
    mysql_CHARSET="utf8",
    mysql_COLLATE="utf8_unicode_ci"
    )
    op.drop_table("monitor_error_flags")
    ### end Alembic commands ###



def downgrade():
    raise NotImplementedError("Rollback is not supported.")
