#!/bin/bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

# Display the version of YOMP in /etc/motd

if [ -d /opt/numenta/YOMP/conf ]; then
  export PYTHONPATH="${PYTHONPATH}:/opt/numenta/YOMP"

  YOMP_VERSION=$(python -c "import YOMP;print YOMP.__version__")
  YOMP_ID=$(python -c "from YOMP.app import config; print config.get('usertrack', 'YOMP_id')")

  echo "YOMP version: ${YOMP_VERSION}"
  echo "YOMPID: ${YOMP_ID}"
else
  echo "YOMP is not installed on this machine."
fi
