#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2015, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
#
# YOMP-preload        Non-standard nginx states
#
# chkconfig: - 20 15
# processname: nginx
# config: /etc/nginx/nginx.conf
# config: /etc/sysconfig/nginx
# pidfile: /var/run/nginx.pid
# description: nginx is an HTTP and reverse proxy server
#
### BEGIN INIT INFO
# Provides: nginx
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop nginx
### END INIT INFO

if [ $(/usr/bin/id -u) -ne 0 ]; then
    echo "You are not root"
    exit 1
fi

# Source function library.
source /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/nginx ]; then
    source /etc/sysconfig/nginx
fi

# We don't want to use the system nginx.conf - we want to use the
# YOMP-api.conf installed as part of YOMP app

source /etc/YOMP/supervisord.vars

prog=nginx
nginx=/usr/sbin/nginx

# Set up different conf files for the varying states.
error_conf="${YOMP_HOME}/conf/nginx-error.conf"
loading_conf="${YOMP_HOME}/conf/nginx-loading.conf"
stopped_conf="${YOMP_HOME}/conf/nginx-stopped.conf"
standard_conf="${YOMP_HOME}/conf/YOMP-api.conf"

lockfile=${LOCKFILE-/var/lock/subsys/nginx}
pidfile=${PIDFILE-/var/run/nginx.pid}

SLEEPMSEC=100000
RETVAL=0

YOMP_error() {
  stop
  cd "${YOMP_HOME}"
  echo -n $"Setting ${prog} status to YOMP_error: "
  logger -t YOMP-preload "Setting ${prog} status to YOMP_error: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${error_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

YOMP_loading() {
  stop
  cd "${YOMP_HOME}"
  echo -n $"Setting ${prog} status to YOMP_loading: "
  logger -t YOMP-preload "Setting ${prog} status to YOMP_loading: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${loading_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

YOMP_stopped() {
  stop
  cd "${YOMP_HOME}"
  echo -n $"Setting ${prog} status to YOMP_stopped: "
  logger -t YOMP-preload "Setting ${prog} status to YOMP_stopped: "

  daemon --pidfile="${pidfile}" "${nginx}" -c "${stopped_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

start_YOMP() {
  echo -n $"Starting ${prog}: "
  logger -t YOMP-preload "starting: "
  daemon --pidfile="${pidfile}" "${nginx}" -c "${standard_conf}"
  RETVAL=$?
  echo
  [ "${RETVAL}" = 0 ] && touch "${lockfile}"
  return "${RETVAL}"
}

stop() {
    echo -n $"Stopping ${prog}: "
    logger -t YOMP-preload "stopping: "
    killproc -p "${pidfile}" "${prog}"
    RETVAL=$?
    echo
    [ "${RETVAL}" = 0 ] && rm -f "${lockfile}" "${pidfile}"
}

reload() {
    cd "${YOMP_HOME}"
    echo -n $"Reloading ${prog}: "
    logger -t YOMP-preload "reloading: "
    killproc -p "${pidfile}" "${prog}" -HUP
    RETVAL=$?
    echo
}

configtest() {
    logger -t YOMP-preload "configtest: "
    nginx -c "${YOMP_HOME}/${YOMP_NGINX_CONF}" -t
}

rh_status() {
    cd "${YOMP_HOME}"
    logger -t YOMP-preload "rh_status: "
    status -p "${pidfile}" "${nginx}"
}

# See how we were called.
case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        YOMP_loading
        ;;
    stop)
        stop
        ;;
    YOMP-loading)
        YOMP_loading
        ;;
    YOMP-error)
        YOMP_error
        ;;
    YOMP-stopped)
        YOMP_stopped
        ;;
    YOMP-start)
        start_YOMP
        ;;
    status)
        rh_status
        RETVAL=$?
        ;;
    restart)
        # configtest -q || exit $RETVAL
        stop
        start
        ;;
    restart-YOMP)
        # configtest -q || exit $RETVAL
        stop
        start_YOMP
        ;;
    upgrade)
        upgrade
        ;;
    condrestart|try-restart)
        if rh_status >/dev/null 2>&1; then
            stop
            start
        fi
        ;;
    force-reload|reload)
        reload
        ;;
    configtest)
        configtest
        ;;
    *)
        echo $"Usage: ${prog} {start|stop|YOMP-error|YOMP-loading|YOMP-stopped|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
        RETVAL=2
esac

exit "${RETVAL}"
